name: learning_course_shop
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  riverpod: ^2.5.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  get_it: ^7.6.7
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  dio: ^5.4.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.3.1
  video_player: ^2.8.2
  webview_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  custom_lint: ^0.6.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter_gen:
  output: lib/core/gen

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/videos/
    - assets/voice/
    - assets/icons/

  uses-material-design: true
